In [1]:
print("Hi! I am Back.")

Hi! I am Back.


In [7]:
a = 10
b = 20
c = a + b
print("the sum is", c)

('the sum is', 30)


In [29]:
from turtle import *
color("red")
begin_fill()
pensize(3)
left(50)
forward(133)
circle(50,200)
right(140)
circle(50,200)
forward(133)
end_fill

<function turtle.end_fill>

In [1]:
x = 10
y = 20
print x,y
print(x+y)

10 20
30


In [3]:
myvar = "John"
_myvar = "john"
my_var = "john"



In [4]:
a = 4
print(a)

A = "sally"
print(A)

print(a)
print(A)

4
sally
4
sally


In [5]:
x = "MRANAL"
for i in x:
    print i
    

M
R
A
N
A
L


In [17]:
fruits = ["apple","banana","cherry"]
x,y,z  = fruits

print x + y + z


applebananacherry


In [19]:
x = "I "
y = "am "
z = "the GODFather"
print(x+y+z)

I am the GODFather


In [22]:
x = "awesome"
def myfunc():
    x = "fantastic"
    print("python is "+x)

myfunc()

print("Python is " +x)

python is fantastic
Python is awesome


In [23]:
x = 10
print x

x = 'john'
print x

10
john


In [25]:
x = "awesome"
def myfunc():
    global x
    x = "fantastic"
    

myfunc()

print("Python is " +x)

Python is fantastic


In [15]:
x = 10
y = "is the best score. "
#print(x + y)

In [18]:
this_list= ["apple",'banana','orange']
print this_list

['apple', 'banana', 'orange']


In [24]:
s = ["banana","orange","mango"]
print s
s1111 = list(("banana","orange","mango"))
print (s1111)



['banana', 'orange', 'mango']


TypeError: 'list' object is not callable

In [20]:
list1 = ['apple','guava','strawberry']

print(type(list1))

<type 'list'>


In [26]:
list6 = ['katrina','kareena ','Bipasha']
list7 = ['sara','alia','kiara']
list8 = ['dharmendra','rajesh','amitabh']
list9 = ['bhai','allu','mahesh']

for x in list6:
    list7.append(x)

print list7   

['sara', 'alia', 'kiara', 'katrina', 'kareena ', 'Bipasha']


In [27]:
for j in list8:
    list9.append(j)

print list9    

['bhai', 'allu', 'mahesh', 'dharmendra', 'rajesh', 'amitabh']


In [31]:
newlist0 = [x for x in range(10)]
newlist1 = [x for x in range(10)if x<5]
newlist2 = [x.upper() for x in list8] 
print newlist0,newlist1,newlist2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0, 1, 2, 3, 4] ['DHARMENDRA', 'RAJESH', 'AMITABH']


In [32]:
joker = [9,8,8,7,7,8]
print joker

[9, 8, 8, 7, 7, 8]


In [34]:
print newlist2

['DHARMENDRA', 'RAJESH', 'AMITABH']


In [35]:
#list:
thislist = ['apple','banana','cherry']
print thislist[1]

thislist = ["bottle Gourd","cucumber","bitter Gourd"]
print thislist[-3]

this_list = ['dalhousie','merry gold','sun flower','jasmine']

banana
bottle Gourd


In [37]:
#SEQUENCES


In [ ]:
#sequence repetition
#Membership testing
#slicing
#Indexing




















In [40]:
list_1 = ['hen ','buffalo','cow','donkey','horse']
list_1.append("cat")
print "\n",list_1

list_1.extend(['c','c#'])
print "\n",list_1

list_1.insert(1,'c')
print "\n",list_1

list_1.remove('c')
print "\n",list_1

print "\n",sorted(list_1)

print "\n",list_1[::-1]


['hen ', 'buffalo', 'cow', 'donkey', 'horse', 'cat']

['hen ', 'buffalo', 'cow', 'donkey', 'horse', 'cat', 'c', 'c#']

['hen ', 'c', 'buffalo', 'cow', 'donkey', 'horse', 'cat', 'c', 'c#']

['hen ', 'buffalo', 'cow', 'donkey', 'horse', 'cat', 'c', 'c#']

['buffalo', 'c', 'c#', 'cat', 'cow', 'donkey', 'hen ', 'horse']

['c#', 'c', 'cat', 'horse', 'donkey', 'cow', 'buffalo', 'hen ']


In [41]:
tuple1 = ('apple','orange','banana')
tuple2 = ('cow','buffalo','lion')
tuple3 = ('kid','man','legend')

print tuple1

('apple', 'orange', 'banana')


In [ ]:
y = list(tuple1)


In [42]:
print tuple1[-1]

banana


In [43]:
print tuple2[1:2]

('buffalo',)


In [2]:
thistuple = ('apple','buffalo','cherry')
if 'apple' in thistuple:
    print "yep!"

yep!


In [47]:
for x in thistuple:
    print(x)

apple
buffalo
cherry


In [50]:
for i in range(len(thistuple)):
    print thistuple[i]

apple
buffalo
cherry


In [3]:
y = list(thistuple)
y.remove ('apple')
print y

['buffalo', 'cherry']


In [5]:
set1 = {'apple','banana','cherry'}
set2 = {1,2,3,4,5,6}
set3 = {'True','False','False'}

print set1,set2,set3

set(['cherry', 'apple', 'banana']) set([1, 2, 3, 4, 5, 6]) set(['False', 'True'])


In [11]:
myset = {"apple","banana","cherry"}
print(type(myset))

<type 'set'>


In [7]:
thisset = set(("apple","banana","cherry"))
print thisset

set(['cherry', 'apple', 'banana'])


In [9]:
for i in thisset:
    print(i)

cherry
apple
banana


In [10]:
print("banana" in thisset)

True


In [5]:
thisset = {"apple","banana","cherry"}
tropical = {"pineapple","mango","papaya"}

print thisset
y = thisset.pop()
print y

print thisset




set(['cherry', 'apple', 'banana'])
cherry
set(['apple', 'banana'])


In [2]:
x = thisset.pop()
print(x)
print(thisset)

mango
set(['papaya', 'apple', 'pineapple', 'cherry', 'banana'])


In [16]:
def compare_to_five(y):
    if y>5:
        return "Greater"
    elif y<0:
        return "Negative"
    elif y<5:
        return "Less"
    else:
        return "equal"

In [9]:
print compare_to_five(10)

Greater


In [14]:
print compare_to_five(-3)

Less


In [11]:
print compare_to_five(3)

Less


In [12]:
print compare_to_five(5)

equal


In [13]:
print compare_to_five(9)

Greater


In [17]:
print compare_to_five(-5)

Negative


In [18]:
x = 1
y = 2.8
z = -3.5

print(type(x))
print(type(y))
print(type(z))

x1 = 35e3
y1 = 12E4
z1 = -87.7e100

print(type(x1))
print(type(y1))
print(type(z1))

<type 'int'>
<type 'float'>
<type 'float'>
<type 'float'>
<type 'float'>
<type 'float'>


In [20]:
x = 3+5j
y = 5j
z = -5i
print(type(x))
print(type(y))
print(type(z))


SyntaxError: invalid syntax (<ipython-input-20-a495615f2b45>, line 3)

In [21]:
def mul(x,y):
    t = x*y
    return t
print mul(9,8)


72


In [22]:
def sub(x,y):
    if x>y:
        return (x-y)
    elif x==y:
        return 0
    else:
        return (y-x)
print sub(8,9)    
    
    

1


In [24]:
print sub(8,8)

0


In [25]:
print sub(9,8)

1


In [26]:
bool("abc")
bool(123)
bool(["apple","cherry","banana"])

True

In [27]:
bool(False)
bool(None)
bool(0)
bool("")
bool(())
bool([])
bool({})

False

In [28]:
def myfun():
    return True

print(myfun())

True


In [29]:
x = "hello"
y = 15

print(bool(x))
print(bool(y))

True
True


In [34]:
def myfunction():
    return False
if myfunction():
    print("Yes!")
else:
    print("No!")

No!


In [33]:
x = 200
print(isinstance(x,float))

False


In [41]:
def fn(str):
    "This print a passed string  into this function"
    print str
    return

fn(4) 
fn("I Love you 3000 ----- Tony Stark ")
fn("I can do it full day ---- Captain America")

4
I Love you 3000 ----- Tony Stark 
I can do it full day ---- Captain America


In [35]:
def fn(mylist):
    mylist.append([1,2,3,4])
    print mylist
    return

mylist = [10,20,30]
fn(mylist)
   

[10, 20, 30, [1, 2, 3, 4]]


In [43]:
def fn(name,age):
    print "Name: ",name
    print "Age: ",age
    return

fn("Mranal",22)

Name:  Mranal
Age:  22


In [44]:
def change(mylist):
    mylist = [1,2,3,4]
    print "Values inside the function: ",mylist
    return
mylist = [10,20,30]
change(mylist)
print "Values Outside the funtion: ",mylist
    

Values inside the function:  [1, 2, 3, 4]
Values Outside the funtion:  [10, 20, 30]


In [45]:
x = 88
x

88

In [46]:
def fn(str):
    "this too shall passed"
    print str
    return
fn(str="My str")

My str


In [47]:
def fn(name,age):
    print "Name: ",name
    print "Age: ",age
    return

fn(name="Mranal",age=22)

Name:  Mranal
Age:  22


In [51]:
def printinfo(name,age = 35):
    "This prints a passed info into this function"
    print "Name: ",name
    print "age:",age
    return
printinfo("Mranal")

Name:  Mranal
age: 35


In [54]:
printinfo(age = 25,name ="Astha")

Name:  Astha
age: 25


In [55]:
def fn(arg1,*x):
    "This prints a variable passed arguments"
    print "Output is: "
    print arg1
    for var in x:
        print("Hi")
        print var
fn(10)
fn(70,60,50)

Output is: 
10
Output is: 
70
Hi
60
Hi
50


In [61]:
def fn(arg1,arg2,*x):
    "This prints a variable passed arguments"
    print "Output is: "
    print arg1
    print arg2
    print x[0],x[1],x[2]
    for var in x:
        print("Hi")
        print var
#fn(10)
fn(70,60,50,60,80,90)

Output is: 
70
60
50 60 80
Hi
50
Hi
60
Hi
80
Hi
90


In [64]:
sum = lambda arg1, arg2: arg1 + arg2
print "value of Total : ",sum(10,20)
print "value of Total : ",sum(20,30)

 value of Total :  30
value of Total :  50


In [66]:
x = lambda a : a+10
print(x(5))

x = lambda a,b:a*b
print(x(5,6))

x= lambda a,b,c :a+b+c
print(x(5,9,5))

15
30
19


In [67]:
def myfunc(n):
    return lambda a: a*n
mydoubler = myfunc(2)

print(mydoubler(11))

22


In [68]:
def myfunc(n):
    return lambda a:a*n
mytripler = myfunc(3)

print(mytripler(22))

66


In [72]:
dict = {1:"Python",2:"Android"}
print(dict)

print(dict[1])


for key in sorted(dict.keys()):
    print(key,'=>',dict[key])
    
dict[1] = "Javascript"
print(dict)

del(dict[2])

print(dict)

print(2 in dict)


{1: 'Python', 2: 'Android'}
Python
(1, '=>', 'Python')
(2, '=>', 'Android')
{1: 'Javascript', 2: 'Android'}
{1: 'Javascript'}
False


In [73]:
str1 = 'learningG' 
print(len(str1))

print(str1.capitalize())

print(str1.upper())

print(str1.lower())
print(str1.find('n'))



9
Learningg
LEARNINGG
learningg
4


In [74]:
thisdict = {
    "brand":"ford","model":"Mustang","year":"1964"
}

print(thisdict["year"])

thisdict

1964


{'brand': 'ford', 'model': 'Mustang', 'year': '1964'}

In [76]:
thisdict = {
    "brand":"ford","model":"Mustang","year":"1964"
}


x= brand.values()
print(x)

car["year"]=2020

thisdict

NameError: name 'brand' is not defined

In [77]:
thisdict = {
    "brand":"ford",
    "model":"Mustang",
    "year" : 1964,  
    "year" : 2020
}

print(thisdict)

{'brand': 'ford', 'model': 'Mustang', 'year': 2020}


In [79]:
thisdict = {
    "brand" : "Ford",
    "electric":False,
    "year":1964,
    "colors":["red","white","blue"]
}

thisdict

{'brand': 'Ford',
 'colors': ['red', 'white', 'blue'],
 'electric': False,
 'year': 1964}

In [80]:
car = {
    "brand" : "Ford",
    "Model" : "Mustang",
    "year"  : "1964"
}

x = car.values()
print(x)

car["year"] = 2020

print(x)

['Ford', 'Mustang', '1964']
['Ford', 'Mustang', '1964']


In [1]:
dic = {}
dict1 = {1:'apple',2:'ball'}

dict2 = {'name':'John',1:[2,4,3]}

dict3 = dict({1:'apple',2:'ball'})

dict4 = dict([(1,'apple'),(2,'ball')])

print(dict1,dict2,dict3,dict4)

({1: 'apple', 2: 'ball'}, {1: [2, 4, 3], 'name': 'John'}, {1: 'apple', 2: 'ball'}, {1: 'apple', 2: 'ball'})


In [4]:
my_dict = {'name':'Jack','age': 44}

print(my_dict['name'])

print(my_dict['age'])

print(my_dict.get('address'))

print(my_dict['address'])

Jack
44
None


KeyError: 'address'

In [10]:
marks = {}.fromkeys(['Maths','English','Science'],0)

print(marks)

for item in marks.items():
    print(item)
print(list(sorted(marks.keys()))) 


{'Maths': 0, 'Science': 0, 'English': 0}
('Maths', 0)
('Science', 0)
('English', 0)
['English', 'Maths', 'Science']


In [11]:
squares = {x: x*x for x in range(6)}

print(squares)

squares = {}

for x in range(6):
    squares[x] = x*x
print(squares)    

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [12]:
square = {1: 1,3: 9,5: 25,7: 49, 9:81}
print(1 in square)

print(2 in square)
 
print( 49 in square)    

True
False
False


In [13]:
for i in square:
    print square[i]

1
9
81
25
49


In [19]:
my_information = {"name": "Dionysia","age":28,"location":"Athens"}

city = my_information.pop('location')
print(my_information)

print(city)



{'age': 28, 'name': 'Dionysia'}
Athens


In [23]:
my_information = {"name": "Dionysia","age":28,"location":"Athens"}

bb = my_information.pop('occupation','Not found')

print(my_information)
print(bb)

{'age': 28, 'name': 'Dionysia', 'location': 'Athens'}
Not found


In [5]:
dic = {
    "child1" :{
    "name":"Emil",
    "year":2004
},
    "child2":{
    "name"  : "Tobias",
    "year"  : 2011
},
    "child3":{
    "name"  :"Linus",
    "year"  :2015
}
   
}

print(dic)





{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2011}, 'child3': {'name': 'Linus', 'year': 2015}}


In [7]:
a1 = {
    
    "name":"Emil",
    "year":2004
}
a2={   
    "name"  : "Tobias",
    "year"  : 2011
}
a3={    
    "name"  :"Linus",
    "year"  :2015
}
   

aa = {
    "child1" : a1,
    "child2" : a2,
    "child3" : a3
}

print(aa)


{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2011}, 'child3': {'name': 'Linus', 'year': 2015}}


In [2]:
str_1 = "Hello Python!"

str_1

str_2 = "Hello"+"Python"
str_2

str_3 = str_1*3
str_3



'Hello Python!Hello Python!Hello Python!'

In [3]:
str_3 = str_1*3
str_3

'Hello Python!Hello Python!Hello Python!'

In [5]:
str_4 = "1 2 3 4 5"


In [6]:
str_4.split()

['1', '2', '3', '4', '5']

In [15]:
str_5 = "1 2 3 4 5"

str_5.split(",")

In [9]:
str_5.split(",")

['1', '2', '3', '4', '5']

In [10]:
str_8 = "   Hello World   "
str_8.strip()

'Hello World'

In [18]:
str_6 = ""

In [19]:
 str_6.join(str_5)

'1 2 3 4 5'

In [20]:
txt = "The best things in life are free!"
if "free" in txt:
    print("Yes,'free' is present.")

Yes,'free' is present.


In [24]:
b = "Hello World!"
print(b[2:5])

b1 = "Hello World!"
print(b1[:5])

b3 = "Hello,world!"
print(b3[-5:-2])

llo
Hello
orl


In [29]:
age = 36
txt = "My name is John. I am "+str(age)
print(txt)

My name is John. I am 36


In [31]:
age = 36
txt = "My name is John,and I am {} "
print(txt.format(age))

My name is John,and I am 36 


In [32]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {2} pieces of item {0} for {1} dollar."

print(myorder.format(quantity, itemno, price))

I want 49.95 pieces of item 3 for 567 dollar.


In [33]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollar."

print(myorder.format(quantity, itemno, price))

I want 3 pieces of item 567 for 49.95 dollar.


In [35]:
a,b,c,d = 10,20,30,40
def FunA():
    a,b,c = 100,200,300
    print("In FunA ",a,b,c,d)
    def FunB():
        a,b = 1000,2000
        print("In FunB ",a,b,c,d)
        def FunC():
            a = 1000
            print("In FunC ",a,b,c,d)
        FunC()
    FunB()
FunA()
print("In_main_",a,b,c,d)

('In FunA ', 100, 200, 300, 40)
('In FunB ', 1000, 2000, 300, 40)
('In FunC ', 1000, 2000, 300, 40)
('In_main_', 10, 20, 30, 40)


In [37]:
import re 
string = "she sells.sea shells.on the.sea shore"
print(re.split(" ",string))

['she', 'sells.sea', 'shells.on', 'the.sea', 'shore']


In [ ]:
#class classname():
    #statement(s)
    

In [ ]:
class Myclass:
    def muppublicmethod(self):
        print*private ,protected and publi

In [1]:
class Infant:
    "This is an example of class"
    pass
child = Infant()
help(child)

Help on instance of Infant in module __main__:

class Infant
 |  This is an example of class



In [7]:
class Infant():
    def walk(self):
        print("started Crawling")
child = Infant()
child.walk()

started Crawling


In [10]:
class Mom():
    def walk(self):
        print("Walk - Mom")
        print("The address of self is",id(self))
class Infant(Mom):
    pass
child = Infant()
child.walk()
print("The address of child is ",id(child))

Walk - Mom
('The address of self is', 80924552L)
('The address of child is ', 80924552L)


In [11]:
gvar = 10
lvar = 200
class Mom():
    lvar = 1100;
    print("global",gvar,"local",lvar)
Mother = Mom()
print("global",gvar,"local")

('global', 10, 'local', 1100)
('global', 10, 'local')


In [1]:
class Example():
    def __init__(self):
        self.__private = "I am Private "
        self._protected = "I am protected"
        self.public = "I am Public"

        ob = Example()
        print(ob.public)
        print(ob._protected)
        print(ob.__private)

In [4]:
class Example():
    def __init__(self):
        self.__private = "I am Private "
        self._protected = "I am protected"
        self.public = "I am Public"
ob = Example()
print(ob.public)
print(ob._protected)
#print(ob.__private)

I am Public
I am protected


In [6]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
class Example():
    def __init__(self):
        print("Object Constructed ")
    def __del__(self):
        print("object destroyed")

obj = Example()
del(obj)

Object Constructed 
object destroyed


In [8]:
class Date:
    def __init__(self,day,month,year):
        self.year = year
        self.month = month
        self.day = day
        
    @classmethod    
    def myd(cls,month,year,day):
        cls.day = day
        cls.month = month
        cls.year = year
        return cls(cls.day,cls.month,cls.year)
    
    @classmethod
    def ymd(cls,month,year,day):
        cls.day = day
        cls.month = month
        cls.year = year
        return cls(cls.day,cls.month,cls.year)
    
d1 = Date(17,4,2019)
print(d1.year,d1.month,d1.day)

d2 = Date(4,2018,15)
print(d2.year,d2.month,d2.day)

d3 = Date(2017,17,1)
print(d3.year,d3.month,d3.day)

print(d1.year)

print(d2.year)

print(d3.year)
            
    

(2019, 4, 17)
(15, 2018, 4)
(1, 17, 2017)
2019
15
1


In [10]:
import numpy as np
arr = np.zeros((5,5))
    
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
import numpy as np
arr = np.linspace((0,5,10))
    
print(arr)

TypeError: linspace() takes at least 2 arguments (1 given)

In [13]:
import numpy as np

In [15]:
lst = [2,5,7,8]

In [16]:
np.array(lst)

array([2, 5, 7, 8])

In [18]:
np.array([lst, lst])

array([[2, 5, 7, 8],
       [2, 5, 7, 8]])

In [19]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
10*np.eye(4)

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [21]:
np.zeros(shape=(4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

5

In [22]:
5*np.ones(shape=(3,5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(-5,10,3)

array([-5, -2,  1,  4,  7])

In [25]:
np.arange(100,10,-5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [26]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [27]:
np.random.rand(2,3,6)

array([[[0.54569341, 0.18607559, 0.73707465, 0.68970269, 0.2735371 ,
         0.24391664],
        [0.33999888, 0.03497416, 0.00481275, 0.97260547, 0.16444279,
         0.5706064 ],
        [0.93843675, 0.11457515, 0.58621535, 0.48066142, 0.36212546,
         0.76863702]],

       [[0.0137132 , 0.31382469, 0.58126339, 0.31763151, 0.50527252,
         0.82341805],
        [0.72271771, 0.26134898, 0.62580141, 0.16896546, 0.04198003,
         0.39687561],
        [0.15883038, 0.80147236, 0.84149153, 0.02226444, 0.01628455,
         0.98054841]]])

In [32]:
mat = np.random.randn(4,5)

In [33]:
mat


array([[-0.89394817, -0.81484522, -0.31320528,  0.42878773,  0.5909674 ],
       [-0.01558432,  1.18753321,  0.08014064,  1.39777376,  0.16238201],
       [ 0.38360577, -0.5771197 , -0.23968501, -0.05182667, -0.45316352],
       [ 0.02140463, -1.19894321,  0.4462497 ,  0.10170068, -0.77601902]])

In [34]:
type(mat)

numpy.ndarray

In [35]:
mat.size

20

In [36]:
mat = np.random.randn(4,5)

In [37]:
mat

array([[ 0.37395023,  1.6327283 ,  0.8118934 , -1.43452563,  0.20388084],
       [ 0.00769467, -2.00635727,  2.25697293,  0.29404958, -0.1903064 ],
       [ 0.50713092,  2.06103214,  1.84125142, -1.10734225,  2.41966113],
       [-1.5849046 , -2.01727833, -1.44754459, -1.12582864,  0.01444333]])

In [45]:
arr = np.arange(50,70)

In [40]:
arr


array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [41]:
arr.shape

(20L,)

In [42]:
arr[4]


54

In [47]:
#arr[start:end]

In [48]:
arr[0:5]

array([50, 51, 52, 53, 54])

In [51]:
import numpy as np
arr = np.array([1,2,3,4],ndmin = 5)

print(arr)
print('number of dimension',arr.ndim)

[[[[[1 2 3 4]]]]]
('number of dimension', 5)


In [52]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [53]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])


[5 6]


In [54]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
print(arr[1,1:4])

[7 8 9]


In [64]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2,3])

[4 9]


In [6]:
import pandas as pd
pd.read_csv(‪"D:\\try.csv")

SyntaxError: invalid syntax (<ipython-input-6-3f17b23543fb>, line 2)

In [7]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '__warningregistry__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_tslib',
 '_ve

In [4]:
import pandas as pd

In [24]:
df = pd.read_csv("D:\\try.csv")
df

Roll No.     Name  Rollno.
0         1   Deepak        9
1         2    Surya       29
2         3   Aniket        4
3         4   Mranal       15
4         5    Ayush        8
5         6   Yuvraj       33
6         7  Prateek       20
7         8   Nikhil       16
8         9    Krati       13
9        10  Apoorva        7

In [9]:
temp = [31,28,31,30,31,30,31,31,30,31,30,31]
mon = ["Jan","Feb","Mar","April","May","June","July","Aug","Sep","Oct","Nov","Dec"]
s1 = pd.Series(temp,mon)
s1


Jan      31
Feb      28
Mar      31
April    30
May      31
June     30
July     31
Aug      31
Sep      30
Oct      31
Nov      30
Dec      31
dtype: int64

In [33]:
df.to_excel("D:\\try1.csv")    

ValueError: No engine for filetype: 'csv'

In [34]:
import pandas as pd

In [36]:
lst = [10,20,30,40,50]

In [38]:
pd.DataFrame(lst)

0
0  10
1  20
2  30
3  40
4  50

In [40]:
import pandas as pd

lst = ['Mranal','Shreya','Parth','Hrishikesh','Hardik','Astha']

pd.DataFrame(lst)

0
0      Mranal
1      Shreya
2       Parth
3  Hrishikesh
4      Hardik
5       Astha

In [58]:
import pandas as pd
data = [['Mranal',22],['parth',21],['Hrishikesh',22],['Hardik',14],['Astha',22],['Shreya',8]]
lst = pd.DataFrame(data,columns = ['Name','Age'],index = ['1','2','3','4','5','6'])


In [59]:
print (lst)

         Name  Age
1      Mranal   22
2       parth   21
3  Hrishikesh   22
4      Hardik   14
5       Astha   22
6      Shreya    8


In [62]:
import numpy as np
import pandas as pd
df = pd.DataFrame()
print df

Empty DataFrame
Columns: []
Index: []


In [ ]:
import pandas as pd
import numpy as np

lst = 

In [64]:
df = pd.DataFrame(['a','b','c','d'])
print df

   0
0  a
1  b
2  c
3  d


In [65]:
for x,n in df.iteritems():
    print(x,n)

(0L, 0    a
1    b
2    c
3    d
Name: 0, dtype: object)


In [67]:
df = pd.DataFrame(np.random.randn(4,4),index=[6,7,8,9],columns = ['col1','col2','col3','col4'])
print(df)

       col1      col2      col3      col4
6  0.202512 -0.156324  0.731607  0.779534
7 -0.139822 -0.298092  1.666090 -1.526541
8 -0.949508 -0.421073 -0.021261  0.751666
9 -0.015207 -1.104561  0.544277 -2.253587


In [68]:
for row_index,row in df.iteritems():
    print(row_index,row)

('col1', 6    0.202512
7   -0.139822
8   -0.949508
9   -0.015207
Name: col1, dtype: float64)
('col2', 6   -0.156324
7   -0.298092
8   -0.421073
9   -1.104561
Name: col2, dtype: float64)
('col3', 6    0.731607
7    1.666090
8   -0.021261
9    0.544277
Name: col3, dtype: float64)
('col4', 6    0.779534
7   -1.526541
8    0.751666
9   -2.253587
Name: col4, dtype: float64)


In [69]:
for row in df.itertuples():
    print (row)

Pandas(Index=6L, col1=0.20251206982577433, col2=-0.15632410080019843, col3=0.7316073137326385, col4=0.7795335634600775)
Pandas(Index=7L, col1=-0.13982211427505192, col2=-0.29809175702039914, col3=1.6660898596192402, col4=-1.5265407625748812)
Pandas(Index=8L, col1=-0.9495081921511227, col2=-0.4210732622383972, col3=-0.021261204731385583, col4=0.7516663138993224)
Pandas(Index=9L, col1=-0.015206929564829478, col2=-1.1045614151085033, col3=0.5442772882053909, col4=-2.253587232812516)


In [72]:
import pandas as pd
A = {'A':['a','b','c'],'B':[1,2,3],'c':[2014,2015,2016],'D':['AA','BB','YY']}
print(A)
df = pd.DataFrame(A)

{'A': ['a', 'b', 'c'], 'c': [2014, 2015, 2016], 'B': [1, 2, 3], 'D': ['AA', 'BB', 'YY']}


In [73]:
data = [{'a':['a','b','c']},{'a':5,'b':10,'c':20},{'a':11,'h':1,'g':6}]
df = pd.DataFrame(data, index =['first','second','th'])
print(df)

                a     b     c    g    h
first   [a, b, c]   NaN   NaN  NaN  NaN
second          5  10.0  20.0  NaN  NaN
th             11   NaN   NaN  6.0  1.0


In [78]:
lst = [[1,2,3],[1,2,3,4]]
df = pd.DataFrame(lst,index = ['m','n'],dtype=float)
print df

     0    1    2    3
m  1.0  2.0  3.0  NaN
n  1.0  2.0  3.0  4.0


In [113]:
import pandas as pd
df = pd.read_csv("C:\\Users\\bhikshum\\Downloads\\titanicnew.csv")
df.head()

pclass  survived                                             name     sex  \
0     1.0       1.0                    Allen, Miss. Elisabeth Walton  female   
1     1.0       1.0                   Allison, Master. Hudson Trevor    male   
2     1.0       0.0                     Allison, Miss. Helen Loraine  female   
3     1.0       0.0             Allison, Mr. Hudson Joshua Creighton    male   
4     1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000    0.0    0.0   24160  211.3375       B5        S    2    NaN   
1   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [88]:
lst1 = [['a','b','c'],[1,2,3]]

df = pd.DataFrame(lst1,columns = ['A','B','C'], dtype = float)
print df

data = [['Alex',10],['Bob',12],['clarke',13]]
df = pd.DataFrame(data,columns = ['Name','Age'],dtype = float)
print df
data  = [[10,'Alex'],[12,'Bob'],[13,'clarke']]

df1 = pd.DataFrame(data,columns = ['Name','Age'],index = [5,6,7],dtype = float)
print df1

   A  B  C
0  a  b  c
1  1  2  3
     Name   Age
0    Alex  10.0
1     Bob  12.0
2  clarke  13.0
   Name     Age
5  10.0    Alex
6  12.0     Bob
7  13.0  clarke


In [85]:
import pandas as pd
lst1 = [['a','b','c'],[1,2,3]]

df = pd.DataFrame(lst1,columns = ['A','B','C'],dtype = float)
print df

   A  B  C
0  a  b  c
1  1  2  3


In [89]:
df = pd.read_csv("D:\\try.csv")
df

Roll No.     Name  Rollno.
0         1   Deepak        9
1         2    Surya       29
2         3   Aniket        4
3         4   Mranal       15
4         5    Ayush        8
5         6   Yuvraj       33
6         7  Prateek       20
7         8   Nikhil       16
8         9    Krati       13
9        10  Apoorva        7

In [91]:
df1 = pd.read_csv("D:\\try2.csv")
df1

Rollno.  cgpa
0        9  7.50
1       29  8.80
2        4  7.50
3       15  7.50
4        8  6.58
5       33  8.00
6       20  7.50
7       16  6.50
8       13  6.40
9        7  7.50

In [103]:
df = pd.read_csv("D:\\try.csv")
df1 = pd.read_csv("D:\\try2.csv")
df2 = pd.concat([df,df1],axis =1)
print df2

   Roll No.     Name  Rollno.  Rollno.  cgpa
0         1   Deepak        9        9  7.50
1         2    Surya       29       29  8.80
2         3   Aniket        4        4  7.50
3         4   Mranal       15       15  7.50
4         5    Ayush        8        8  6.58
5         6   Yuvraj       33       33  8.00
6         7  Prateek       20       20  7.50
7         8   Nikhil       16       16  6.50
8         9    Krati       13       13  6.40
9        10  Apoorva        7        7  7.50


In [112]:
df = pd.read_csv("D:\\prac.csv")
df1 = pd.read_csv("D:\\prac2.csv")
df2 =df.merge(df1 ,how= 'inner',on = 'Student_id')
print df2

   Student_id First_name Last_name  Marks
0   180105015    Mranal    Bhikshu     65
1   180105004     Aniket     Verma     85
2   180105009     Deepak     Yadav     62
3   180105029      Surya   Prakash     65
4   180105033     Yuvraj     Singh     56
5   180105016     Nikhil     Yadav     75
6   180105034    shiksha   Dwevedi     65


In [118]:
import pandas as pd
df = pd.read_csv("C:\\Users\\bhikshum\\Downloads\\titanicnew.csv")
df
df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [127]:
df.iloc[0:5,1:3]

survived                                             name
0       1.0                    Allen, Miss. Elisabeth Walton
1       1.0                   Allison, Master. Hudson Trevor
2       0.0                     Allison, Miss. Helen Loraine
3       0.0             Allison, Mr. Hudson Joshua Creighton
4       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)

In [125]:
df.iloc[0:5]

pclass  survived                                             name     sex  \
0     1.0       1.0                    Allen, Miss. Elisabeth Walton  female   
1     1.0       1.0                   Allison, Master. Hudson Trevor    male   
2     1.0       0.0                     Allison, Miss. Helen Loraine  female   
3     1.0       0.0             Allison, Mr. Hudson Joshua Creighton    male   
4     1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000    0.0    0.0   24160  211.3375       B5        S    2    NaN   
1   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [132]:
df['name'][0:10]

0                      Allen, Miss. Elisabeth Walton
1                     Allison, Master. Hudson Trevor
2                       Allison, Miss. Helen Loraine
3               Allison, Mr. Hudson Joshua Creighton
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
5                                Anderson, Mr. Harry
6                  Andrews, Miss. Kornelia Theodosia
7                             Andrews, Mr. Thomas Jr
8      Appleton, Mrs. Edward Dale (Charlotte Lamson)
9                            Artagaveytia, Mr. Ramon
Name: name, dtype: object

In [140]:
gh = df['name'][0:10]
gh

0                      Allen, Miss. Elisabeth Walton
1                     Allison, Master. Hudson Trevor
2                       Allison, Miss. Helen Loraine
3               Allison, Mr. Hudson Joshua Creighton
4    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
5                                Anderson, Mr. Harry
6                  Andrews, Miss. Kornelia Theodosia
7                             Andrews, Mr. Thomas Jr
8      Appleton, Mrs. Edward Dale (Charlotte Lamson)
9                            Artagaveytia, Mr. Ramon
Name: name, dtype: object

In [145]:
hj = df[['name','age']][0:10]
hj

name      age
0                    Allen, Miss. Elisabeth Walton  29.0000
1                   Allison, Master. Hudson Trevor   0.9167
2                     Allison, Miss. Helen Loraine   2.0000
3             Allison, Mr. Hudson Joshua Creighton  30.0000
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000
5                              Anderson, Mr. Harry  48.0000
6                Andrews, Miss. Kornelia Theodosia  63.0000
7                           Andrews, Mr. Thomas Jr  39.0000
8    Appleton, Mrs. Edward Dale (Charlotte Lamson)  53.0000
9                          Artagaveytia, Mr. Ramon  71.0000

In [150]:
df = pd.read_csv("D:\\text.txt")
df

Name               Quality
0     Mranal             He is a Good Boy.
1  Parth                He is intelligent.
2             Hrishikesh       He is Calm.
3  Hardik             He is Coooodddderrr.

In [151]:
df.head()

Name               Quality
0     Mranal             He is a Good Boy.
1  Parth                He is intelligent.
2             Hrishikesh       He is Calm.
3  Hardik             He is Coooodddderrr.

In [160]:
df = pd.read_csv("D:\\netflix_titles.csv")
df


show_id     type                                              title  \
0         s1    Movie                               Dick Johnson Is Dead   
1         s2  TV Show                                      Blood & Water   
2         s3  TV Show                                          Ganglands   
3         s4  TV Show                              Jailbirds New Orleans   
4         s5  TV Show                                       Kota Factory   
5         s6  TV Show                                      Midnight Mass   
6         s7    Movie                   My Little Pony: A New Generation   
7         s8    Movie                                            Sankofa   
8         s9  TV Show                      The Great British Baking Show   
9        s10    Movie                                       The Starling   
10       s11  TV Show                Vendetta: Truth, Lies and The Mafia   
11       s12  TV Show                                   Bangkok Breaking   
12       s13    Movie                                       Je Suis Karl   
13       s14    Movie                   Confessions of an Invisible Girl   
14       s15  TV Show                    Crime Stories: India Detectives   
15       s16  TV Show                                  Dear White People   
16       s17    Movie  Europe's Most Dangerous Man: Otto Skorzeny in ...   
17       s18  TV Show                                    Falsa identidad   
18       s19    Movie                                          Intrusion   
19       s20  TV Show                                             Jaguar   
20       s21  TV Show    Monsters Inside: The 24 Faces of Billy Milligan   
21       s22  TV Show                             Resurrection: Ertugrul   
22       s23    Movie                                    Avvai Shanmughi   
23       s24    Movie       Go! Go! Cory Carson: Chrissy Takes the Wheel   
24       s25    Movie                                              Jeans   
25       s26  TV Show                               Love on the Spectrum   
26       s27    Movie                                     Minsara Kanavu   
27       s28    Movie                                          Grown Ups   
28       s29    Movie                                         Dark Skies   
29       s30    Movie                                           Paranoia   
...      ...      ...                                                ...   
8777   s8778    Movie                                          Yes or No   
8778   s8779    Movie                                        Yes or No 2   
8779   s8780    Movie                                      Yes or No 2.5   
8780   s8781  TV Show                                       Yo-Kai Watch   
8781   s8782    Movie                            Yo-Kai Watch: The Movie   
8782   s8783    Movie                                        Yoga Hosers   
8783   s8784  TV Show                                               Yoko   
8784   s8785    Movie                               Yoko and His Friends   
8785   s8786  TV Show                                                YOM   
8786   s8787    Movie                                       You Can Tutu   
8787   s8788    Movie                          You Can’t Fight Christmas   
8788   s8789    Movie                                       You Carry Me   
8789   s8790    Movie                                You Changed My Life   
8790   s8791    Movie                      You Don't Mess with the Zohan   
8791   s8792    Movie                                        Young Adult   
8792   s8793    Movie                                        Young Tiger   
8793   s8794    Movie                               Yours, Mine and Ours   
8794   s8795    Movie                                             اشتباك   
8795   s8796  TV Show                                    Yu-Gi-Oh! Arc-V   
8796   s8797  TV Show                                         Yunus Emre   
8797   s8798  TV Show                                

In [162]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [195]:
df1 = df.fillna({
    'director':'Mranal Bhikshu',
    'country' :'India',
    'cast'    :'Parth Shukla, Hardik Batheja, Hrishikesh Shukla',
    'date_added':'February 29,2022',
    'rating'    :'TV-MA',
    'duration'  :'90 min'
})
df1

show_id     type                                              title  \
0         s1    Movie                               Dick Johnson Is Dead   
1         s2  TV Show                                      Blood & Water   
2         s3  TV Show                                          Ganglands   
3         s4  TV Show                              Jailbirds New Orleans   
4         s5  TV Show                                       Kota Factory   
5         s6  TV Show                                      Midnight Mass   
6         s7    Movie                   My Little Pony: A New Generation   
7         s8    Movie                                            Sankofa   
8         s9  TV Show                      The Great British Baking Show   
9        s10    Movie                                       The Starling   
10       s11  TV Show                Vendetta: Truth, Lies and The Mafia   
11       s12  TV Show                                   Bangkok Breaking   
12       s13    Movie                                       Je Suis Karl   
13       s14    Movie                   Confessions of an Invisible Girl   
14       s15  TV Show                    Crime Stories: India Detectives   
15       s16  TV Show                                  Dear White People   
16       s17    Movie  Europe's Most Dangerous Man: Otto Skorzeny in ...   
17       s18  TV Show                                    Falsa identidad   
18       s19    Movie                                          Intrusion   
19       s20  TV Show                                             Jaguar   
20       s21  TV Show    Monsters Inside: The 24 Faces of Billy Milligan   
21       s22  TV Show                             Resurrection: Ertugrul   
22       s23    Movie                                    Avvai Shanmughi   
23       s24    Movie       Go! Go! Cory Carson: Chrissy Takes the Wheel   
24       s25    Movie                                              Jeans   
25       s26  TV Show                               Love on the Spectrum   
26       s27    Movie                                     Minsara Kanavu   
27       s28    Movie                                          Grown Ups   
28       s29    Movie                                         Dark Skies   
29       s30    Movie                                           Paranoia   
...      ...      ...                                                ...   
8777   s8778    Movie                                          Yes or No   
8778   s8779    Movie                                        Yes or No 2   
8779   s8780    Movie                                      Yes or No 2.5   
8780   s8781  TV Show                                       Yo-Kai Watch   
8781   s8782    Movie                            Yo-Kai Watch: The Movie   
8782   s8783    Movie                                        Yoga Hosers   
8783   s8784  TV Show                                               Yoko   
8784   s8785    Movie                               Yoko and His Friends   
8785   s8786  TV Show                                                YOM   
8786   s8787    Movie                                       You Can Tutu   
8787   s8788    Movie                          You Can’t Fight Christmas   
8788   s8789    Movie                                       You Carry Me   
8789   s8790    Movie                                You Changed My Life   
8790   s8791    Movie                      You Don't Mess with the Zohan   
8791   s8792    Movie                                        Young Adult   
8792   s8793    Movie                                        Young Tiger   
8793   s8794    Movie                               Yours, Mine and Ours   
8794   s8795    Movie                                             اشتباك   
8795   s8796  TV Show                                    Yu-Gi-Oh! Arc-V   
8796   s8797  TV Show                                         Yunus Emre   
8797   s8798  TV Show                                

In [191]:
df1.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [192]:
df1

show_id     type                                              title  \
0         s1    Movie                               Dick Johnson Is Dead   
1         s2  TV Show                                      Blood & Water   
2         s3  TV Show                                          Ganglands   
3         s4  TV Show                              Jailbirds New Orleans   
4         s5  TV Show                                       Kota Factory   
5         s6  TV Show                                      Midnight Mass   
6         s7    Movie                   My Little Pony: A New Generation   
7         s8    Movie                                            Sankofa   
8         s9  TV Show                      The Great British Baking Show   
9        s10    Movie                                       The Starling   
10       s11  TV Show                Vendetta: Truth, Lies and The Mafia   
11       s12  TV Show                                   Bangkok Breaking   
12       s13    Movie                                       Je Suis Karl   
13       s14    Movie                   Confessions of an Invisible Girl   
14       s15  TV Show                    Crime Stories: India Detectives   
15       s16  TV Show                                  Dear White People   
16       s17    Movie  Europe's Most Dangerous Man: Otto Skorzeny in ...   
17       s18  TV Show                                    Falsa identidad   
18       s19    Movie                                          Intrusion   
19       s20  TV Show                                             Jaguar   
20       s21  TV Show    Monsters Inside: The 24 Faces of Billy Milligan   
21       s22  TV Show                             Resurrection: Ertugrul   
22       s23    Movie                                    Avvai Shanmughi   
23       s24    Movie       Go! Go! Cory Carson: Chrissy Takes the Wheel   
24       s25    Movie                                              Jeans   
25       s26  TV Show                               Love on the Spectrum   
26       s27    Movie                                     Minsara Kanavu   
27       s28    Movie                                          Grown Ups   
28       s29    Movie                                         Dark Skies   
29       s30    Movie                                           Paranoia   
...      ...      ...                                                ...   
8777   s8778    Movie                                          Yes or No   
8778   s8779    Movie                                        Yes or No 2   
8779   s8780    Movie                                      Yes or No 2.5   
8780   s8781  TV Show                                       Yo-Kai Watch   
8781   s8782    Movie                            Yo-Kai Watch: The Movie   
8782   s8783    Movie                                        Yoga Hosers   
8783   s8784  TV Show                                               Yoko   
8784   s8785    Movie                               Yoko and His Friends   
8785   s8786  TV Show                                                YOM   
8786   s8787    Movie                                       You Can Tutu   
8787   s8788    Movie                          You Can’t Fight Christmas   
8788   s8789    Movie                                       You Carry Me   
8789   s8790    Movie                                You Changed My Life   
8790   s8791    Movie                      You Don't Mess with the Zohan   
8791   s8792    Movie                                        Young Adult   
8792   s8793    Movie                                        Young Tiger   
8793   s8794    Movie                               Yours, Mine and Ours   
8794   s8795    Movie                                             اشتباك   
8795   s8796  TV Show                                    Yu-Gi-Oh! Arc-V   
8796   s8797  TV Show                                         Yunus Emre   
8797   s8798  TV Show                                

In [193]:
df1.duplicated()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...  
8777    False
8778    False
8779    False
8780    False
8781    False
8782    False
8783    False
8784    False
8785    False
8786    False
8787    False
8788    False
8789    False
8790    False
8791    False
8792    False
8793    False
8794    False
8795    False
8796    False
8797    False
8798    False
8799    False
8800    False
8801    False
8802    False
8803    False
8804    False
8805    False
8806    False
Length: 8807, dtype: bool

In [189]:
df1.duplicated().sum()

0